### ISSUE TITLE
Should not use Synchronous XMLHttpRequest for fetching data

### ISSUE THREAD

**Issue by gasolin** [gitcoinco/browser-extension#42]
Synchronous XMLHttpRequest on the main thread is deprecated because of its detrimental effects to the end user’s experience. For more help http://xhr.spec.whatwg.org/

If user intalled chrome_ext, The github page will hang a while when user's network speed is not fast enough.

**Comment by xwartz** [comment]
+1

**Comment by owocki** [comment]
related : https://github.com/gitcoinco/chrome_ext/issues/43

**Comment by owocki** [comment]
03307f8b8c46fdc4679dcb882d047e8e4b55c4a0

**Comment by owocki** [comment]
publishing to the chrome store now

**Comment by gasolin** [comment]
`functions.js` still using sync XMLHttpRequest, we should fix that
